[package]
name = "rav1e"
version = "0.1.0"
authors = ["Thomas Daede <tdaede@xiph.org>"]
build = "build.rs"
include = ["/src/**", "/aom_build/**", "/Cargo.toml"]

[dependencies]
bitstream-io = "0.6"
byteorder = "1"
clap = "2"
libc = "0.2"
rand = "0.4"
rustyline = "1"
y4m = "0.1"

[build-dependencies]
cc = "1"

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "predict"
harness = false
